Alex Piven w1 UsingAPIs
HackYourAssignment/Assignments-Cohort50 pull request #25
Opened 2024-10-05 19:32 UTC by op117

completed exercises of the UsingAPIs module

2024-11-10 15:20 UTC, pkazmierczak requested changes
Hey @op117, this looks mostly good, but ex4 lacks an explanation for why in case of rejected promises dice that have not yet finished their roll continue to do so. 

Can you add a comment with an explanation?

2024-11-10 15:20 UTC, pkazmierczak commented on 3-UsingAPIs/Week1/assignment/ex4-pokerDiceAll.js
> +  const diceRolls = dice.map((_, index) => rollDie(index + 1));
```suggestion
  const diceRolls = dice.map((index) => rollDie(index));
```

I think that's equivalent and somewhat... more readable/understandable?

2024-11-10 20:18 UTC, op117 commented
Hey @pkazmierczak, fixed. 
You can check the latest commit. How it works now:
1. Promise.all() rejects as soon as the first promise is rejected.
2. The remaining asynchronous operations continue executing independently because each call to rollDie() initiates its roll immediately. Since Promise.all() cannot stop or cancel them, these rolls continue in the background, even if one promise has already been rejected.

2024-11-11 08:33 UTC, pkazmierczak approved these changes
Nice one, thanks for a quick response!
LGTM 👍

2025-03-09 10:22 UTC, closed without merging